<?php

return [

    'trains' => [
        [
            'company' => 'LaraTRAIN',
            'arrival_station' => 'Roma',
            'departure_station' => 'Milano',
            'departure_time' => '2024-05-15 10:10:10',
            'arrival_time' => '2024-05-15 12:58:10',
            'train_id' => '22222',
            'vagons_number' => '12',
            'is_in_time' => '1',
            'is_deleted' => '0',
        ],
        [
            'company' => 'LaraTRAIN',
            'arrival_station' => 'Milano',
            'departure_station' => 'Roma',
            'departure_time' => '2024-05-05 11:11:11',
            'arrival_time' => '2024-05-05 13:51:11',
            'train_id' => '31478',
            'vagons_number' => '12',
            'is_in_time' => '1',
            'is_deleted' => '0',
        ],
        [
            'company' => 'LaraTRAIN',
            'arrival_station' => 'Milano',
            'departure_station' => 'Varese',
            'departure_time' => '2024-05-10 14:11:40',
            'arrival_time' => '2024-05-10 15:11:40',
            'train_id' => '25520',
            'vagons_number' => '10',
            'is_in_time' => '0',
            'is_deleted' => '0',
        ],
        [
            'company' => 'LaraTRAIN',
            'arrival_station' => 'Varese',
            'departure_station' => 'Milano',
            'departure_time' => '2024-05-10 16:32:50',
            'arrival_time' => '2024-05-10 17:24:00',
            'train_id' => '12345',
            'vagons_number' => '8',
            'is_in_time' => '0',
            'is_deleted' => '1',
        ],
        [
            'company' => 'LaraTRAIN',
            'arrival_station' => 'Venezia',
            'departure_station' => 'Verona',
            'departure_time' => '2024-05-11 09:48:12',
            'arrival_time' => '2024-05-11 10:58:12',
            'train_id' => '23451',
            'vagons_number' => '5',
            'is_in_time' => '1',
            'is_deleted' => '0',
        ],
        [
            'company' => 'LaraTRAIN',
            'arrival_station' => 'Verona',
            'departure_station' => 'Venezia',
            'departure_time' => '2024-05-11 11:32:12',
            'arrival_time' => '2024-05-11 12:44:12',
            'train_id' => '23441',
            'vagons_number' => '8',
            'is_in_time' => '1',
            'is_deleted' => '0',
        ],
        [
            'company' => 'LaraTRAIN',
            'arrival_station' => 'Milano',
            'departure_station' => 'Torino',
            'departure_time' => '2024-05-13 08:23:12',
            'arrival_time' => '2024-05-13 09:22:12',
            'train_id' => '22451',
            'vagons_number' => '7',
            'is_in_time' => '0',
            'is_deleted' => '0',
        ],
        [
            'company' => 'LaraTRAIN',
            'arrival_station' => 'Torino',
            'departure_station' => 'Milano',
            'departure_time' => '2024-05-11 09:48:12',
            'arrival_time' => '2024-05-11 10:48:12',
            'train_id' => '23351',
            'vagons_number' => '12',
            'is_in_time' => '0',
            'is_deleted' => '1',
        ],
    ]
];
